### ISSUE TITLE
PyQT5 Research

### ISSUE THREAD

**Issue by datapsyche** [bangalorebyte-cohort28-1910/Csv_Uploader_Project#5]
As a dev,  I should be able to take a session for 45mins (30min session+15min QA).
I should be able to teach others to build a calculator using PyQT5
https://realpython.com/python-pyqt-gui-calculator/

**Comment by suvarna-jp** [comment]
Reference links 

https://realpython.com/python-pyqt-gui-calculator/
https://build-system.fman.io/pyqt5-tutorial
